"""Remove unique constraint from product no

Revision ID: <auto-generated-revision-id>
Revises: <previous-revision-id>
Create Date: <auto-generated-date>

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '<auto-generated-revision-id>'
down_revision = '<previous-revision-id>'
branch_labels = None
depends_on = None

def upgrade():
    # Remove the UNIQUE constraint from the 'no' column
    with op.batch_alter_table('product') as batch_op:
        batch_op.drop_constraint('uq_product_no', type_='unique')

def downgrade():
    # Add the UNIQUE constraint back if needed
    with op.batch_alter_table('product') as batch_op:
        batch_op.create_unique_constraint('uq_product_no', ['no'])